# Generated by Django 4.1 on 2022-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
